### ISSUE TITLE
Follow along TDD: Create tests for simple input

### ISSUE THREAD

**Issue by ankushdharkar** [RealDevSquad/react-tests-tdd#35]
Create specs for an input component named `<StarbucksInput>`

**15-30 min React Exercise**

- [ ] Task: Make all tests pass

1. Fork and clone the repo, checkout to _develop_ branch, install the packages

2. Run `yarn test`
Things will pass, because the test cases in the spec is not enabled to run yet.

3. Go to the specs file: [Link to index.spec.js](https://github.com/Real-Dev-Squad/react-tests-tdd/blob/develop/src/components/starbucks-input/index.spec.js)
It has details for you to implement a simple input component

4. On line 5 of that specs file, change `describe.skip` to say just `describe` (remove `.skip` keyword)

3. Then run `yarn test` again
This time, it will fail (because there is no component that satisfies the cases)

4. **WRITE** that component according to the spec. Make all the tests pass. You are not allowed to change anything in the tests file.

It's a very simple react component you have to write. 

Read the test cases first. Are you able to understand what your component should do?

**Comment by yesyash** [comment]
#### My Component: 
[https://github.com/yesyash/react-tests-tdd/blob/develop/src/components/starbucks-input/index.js](https://github.com/yesyash/react-tests-tdd/blob/develop/src/components/starbucks-input/index.js)

**Comment by lakshayman** [comment]
https://github.com/lakshayman/react-tests-tdd/blob/develop/src/components/starbucks-input/index.js

**Comment by bhtibrewal** [comment]
https://github.com/bhtibrewal/react-tests-tdd/tree/develop/src
passed tests

**Comment by aakankshadhurandhar** [comment]
passed test : 
[LINK](https://github.com/aakankshadhurandhar/react-tests-tdd/blob/develop/src/components/starbucks-input/index.js)
![Screenshot from 2022-12-03 12-59-27](https://user-images.githubusercontent.com/34390765/205430217-113be24a-2243-4a8f-861c-91340c703033.png)

**Comment by SanketDhabarde** [comment]
Passed test: https://github.com/SanketDhabarde/react-tests-tdd/blob/develop/src/components/starbucks-input/index.js
![Screenshot (366)](https://user-images.githubusercontent.com/40385118/205430705-c10ad41b-8c7d-4d18-88d8-3585cdb014f8.png)

**Comment by vikhyat187** [comment]
Test cases passed.
https://github.com/vikhyat187/react-tests-tdd/blob/develop/src/components/starbucks-input/index.js
![testcases](https://user-images.githubusercontent.com/52795644/205442199-a9fb33e9-437a-476b-9e83-2f981cac6aef.jpg)

**Comment by Tejs1** [comment]
https://github.com/Tejs1/react-tests-tdd/blob/develop/src/components/starbucks-input/index.js
![image](https://user-images.githubusercontent.com/67797070/205448632-edfbd2bf-0b61-4214-a5eb-321028ff7fca.png)

**Comment by Muralidhar22** [comment]
https://github.com/Muralidhar22/react-tests-tdd/blob/develop/src/components/starbucks-input/index.js

![image](https://user-images.githubusercontent.com/33935339/205538730-50ddce62-2707-43b6-a3f0-b153a7c9a7eb.png)

**Comment by aakashjangra** [comment]
![image](https://user-images.githubusercontent.com/95037464/205821409-2c059ffc-a453-4c2e-9d76-741ac691750b.png)

Commit - https://github.com/Real-Dev-Squad/react-tests-tdd/commit/28553e6436200677eeb5ff6b24672feb911e3cb4

**Comment by vinit717** [comment]
![Screenshot (128)](https://user-images.githubusercontent.com/111434418/205901648-c42546c2-38cd-4acc-a5ed-9602819bdde4.png)

**Comment by kush-x7** [comment]
https://github.com/kush-x7/My-first-rds-test/blob/main/src/components/starbucks-input/index.js
<img width="190" alt="image" src="https://user-images.githubusercontent.com/58984939/205911217-4f2708b6-7fe2-4623-b182-0d68c5b5fa2c.png">

**Comment by Maheima** [comment]
![image](https://user-images.githubusercontent.com/42349041/206071187-52a9e7a9-11ce-4224-8d32-c609b5c821ab.png)

**Comment by Maheima** [comment]
https://github.com/Maheima/react-tests-tdd/blob/develop/src/components/starbucks-input/index.js

**Comment by samyakshah3008** [comment]
Link: https://github.com/samyakshah3008/react-tests-tdd/blob/develop/src/components/starbucks-input/StarbucksInput.jsx 

![image](https://user-images.githubusercontent.com/86982322/206273346-c4aeda49-1af4-4c5b-8aee-1c2897e73cee.png)

**Comment by satyam73** [comment]
https://github.com/satyam73/react-tests-tdd
![image](https://user-images.githubusercontent.com/85296770/206277622-8b79f6cf-1657-4f3f-baca-b64056bb5063.png)

**Comment by ranitasahaa1230** [comment]
https://github.com/ranitasahaa1230/react-tests-tdd/blob/develop/src/components/starbucks-input/index.js

![image](https://user-images.githubusercontent.com/37957073/206330797-efa6403e-c435-42b0-a917-d402e6e1bbcd.png)

**Comment by Vedant-Manjrekar** [comment]
Done 👍🏽
Link 🔗: https://github.com/Vedant-Manjrekar/react-tests-tdd/blob/develop/src/components/starbucks-input/StarbucksInput.js

### SS:
<img width="534" alt="Screenshot 2022-12-09 at 4 50 36 PM" src="https://user-images.githubusercontent.com/93585735/206692794-68a30185-9cf8-4e21-a2f8-36a292bcaa11.png">

**Comment by iRohitGaur** [comment]
Link: https://github.com/iRohitGaur/rds-react-tests-tdd/blob/develop/src/components/starbucks-input/index.js
<img width="454" alt="Screenshot 2022-12-09 at 2 03 06 PM" src="https://user-images.githubusercontent.com/10892977/206778357-5a62e89f-90b9-4610-aa1d-d7467f8036c9.png">

**Comment by manish591** [comment]
Passed Tests

LINK: https://github.com/manish591/react-tests-tdd/tree/develop/src

![Screenshot (34)](https://user-images.githubusercontent.com/79859472/206852147-20c1c279-3309-4621-a137-fb20112a61d2.png)
