### ISSUE TITLE
Package Upgrades

### ISSUE THREAD

**Issue by Mir-SA** [RealDevSquad/react-tests-tdd#59]
### Issue Description

There are few packages with minor updates and patches which needs to be updated.

### Expected Behavior

All packages should be up-to-date.

### Current Behavior

2 of them have new updates.

### Screenshots

![image](https://github.com/user-attachments/assets/7e0dd8b3-b037-4fac-9960-35e470e707fc)

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. `yarn outdated`

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [x] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by Kami-prog** [comment]
This might help:This file might fix it

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)
